// <auto-generated />
using System;
using BikeRentalSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BikeRentalSystem.Migrations
{
    [DbContext(typeof(BikeRentalContext))]
    [Migration("20230413085951_tworzenie_bazy")]
    partial class tworzenie_bazy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BikeRentalSystem.Models.Rent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("PhoneNumberDriver")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emailDriver")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstNameDriver")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("rentStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("rentStop")
                        .HasColumnType("datetime2");

                    b.Property<string>("secondNameDriver")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("vehicleId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Rents");
                });

            modelBuilder.Entity("BikeRentalSystem.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HourlyPrize")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wheel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Vehicle");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BikeRentalSystem.Models.Bike", b =>
                {
                    b.HasBaseType("BikeRentalSystem.Models.Vehicle");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Vehicles", t =>
                        {
                            t.Property("Size")
                                .HasColumnName("Bike_Size");
                        });

                    b.HasDiscriminator().HasValue("Bike");
                });

            modelBuilder.Entity("BikeRentalSystem.Models.Scooter", b =>
                {
                    b.HasBaseType("BikeRentalSystem.Models.Vehicle");

                    b.Property<bool>("Electric")
                        .HasColumnType("bit");

                    b.Property<int>("Hight")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Scooter");
                });

            modelBuilder.Entity("BikeRentalSystem.Models.Skates", b =>
                {
                    b.HasBaseType("BikeRentalSystem.Models.Vehicle");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<int>("WheelHardness")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Skates");
                });
#pragma warning restore 612, 618
        }
    }
}
